### ISSUE TITLE
Use docker hub trusted build service

### ISSUE THREAD

**Issue by djdefi** [gwos/groundwork-docker-container#1]
I noticed this image is on the public [docker hub](https://registry.hub.docker.com/u/gwos/groundwork-docker-container/), however the trusted build service is not being utilized.

The provided instructions mention doing a build directly from this github repo, so I am not sure why you are doing a manual push to the docker hub. This is a critical piece for being able to audit the contents of your image.

**Comment by hanskriel** [comment]
GroundWork application is built from 95 different Open Source projects and it is more complex than anything that is in docker repo.

**Comment by djdefi** [comment]
@hanskriel that is impressive. 

My question was more directed at the fact that the build process for the image uses a standard `docker build` which is exactly what [Automated builds](https://docs.docker.com/docker-hub/builds/) on the Docker Hub do. It seems like it would be trivial to make use of this service, unless there is some issue that I am unaware of with the Docker official build environment.
